### ISSUE TITLE
why not ssr

### ISSUE THREAD

**Issue by HeyCrab3** [Lala-0x3f/Sencraft-guide#4]
作为文档网站 SSR还是很必要的
尽管nuxt的ssr不那么好用
但是能加快加载速度啊

**Comment by Lala-0x3f** [comment]
![Screenshot 2024-03-23 115956](https://github.com/Lala-0x3f/Sencraft-guide/assets/93862679/beea8a12-ba4e-4a4f-b14a-48ea5a407490)
应该解决了
